modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/jaquadro/ExtraButtons/issues"
displayURL="https://minecraft.curseforge.com/projects/extrabuttons"
authors="Texelsaur"
license="MIT"

[[mods]]
    modId="extrabuttons"
    version="${file.jarVersion}"
    displayName="ExtraButtons"
    description='''
    Adds various extra buttons and trigger-like blocks
    '''

[[dependencies.extrabuttons]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extrabuttons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"