modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/jaquadro/ExtraButtons/issues"
displayURL="https://minecraft.curseforge.com/projects/extrabuttons"
authors="Texelsaur"

[[mods]]
    modId="extrabuttons"
    version="${version}"
    displayName="ExtraButtons"
    description='''
    Adds various extra buttons and trigger-like blocks
    '''

[[dependencies.extrabuttons]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extrabuttons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,)"
    ordering="NONE"
    side="BOTH"